{
    "name": "Dojo CRM — Lead to Member Pipeline",
    "version": "19.0.1.0.0",
    "summary": "CRM stages, automations, and convert-to-member flow for the trial → subscription pipeline",
    "author": "Dojo",
    "category": "Martial Arts",
    "license": "LGPL-3",
    "depends": [
        "crm",
        "dojo_members",
        "dojo_communications",
        "dojo_subscriptions",
        "dojo_classes",
        "sms",
        "mail",
        "base_automation",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/crm_tag.xml",
        "data/crm_stage.xml",
        "data/mail_template_crm.xml",
        "data/base_automation.xml",
        "data/ir_cron.xml",
        "views/dojo_book_trial_wizard_view.xml",
        "views/dojo_convert_lead_wizard_view.xml",
        "views/crm_lead_view_inherit.xml",
        "views/dojo_member_view_crm_inherit.xml",
    ],
    "installable": True,
    "auto_install": False,
}
