{
    "name": "Dojo Subscriptions",
    "summary": "Membership plans and subscriptions",
    "version": "19.0.4.1.0",
    "category": "Services",
    "license": "LGPL-3",
    "author": "Dojo",
    "depends": ["dojo_members", "account", "dojo_classes"],
    "data": [
        "security/ir.model.access.csv",
        "security/dojo_subscriptions_security.xml",
        "data/membership_product.xml",
        "data/mail_template_dunning.xml",
        "data/ir_cron.xml",
        "views/dojo_program_enrollment_views.xml",
        "views/dojo_subscription_views.xml",
    ],
    "post_init_hook": "populate_program_enrollments",
    "application": True,
    "auto_install": True,
    "installable": True,
}
